export interface Ticket {
    id?: number,
    showTime: Date,
    cityId: string,
    cityName: string,
    price: number,
    title: string,
    subTitle: string,
    remainNumber: number,
    soldOut: boolean,
    completeShow: boolean,
    open: boolean,
    imageBase64: string,
    purchaseDeadLine: Date,
}
